languageName: 日本語 (Japanese)
params:
  description: NumPyが広く利用される理由 強力な多次元配列、数値計算ツール群、相互運用性、高いパフォーマンス、オープンソース
  navbarlogo:
    image: logo.svg
    text: NumPy
    link: /ja/
  hero:
    #Main hero title
    title: NumPy
    #Hero subtitle (optional)
    subtitle: Pythonによる科学技術計算の基礎パッケージ
    #Button text
    buttontext: "最新リリース: Numpy 1.25. すべてのリリースを表示する"
    #Where the main hero button links to
    buttonlink: "/ja/news/#releases"
    #Hero image (from static/images/___)
    image: logo.svg
  shell:
    title: placeholder
    intro:
      - 
        title: NumPy を試す
        text: インタラクティブシェルを使用して、ブラウザ上で Numpy を試してみてください。
    docslink: <a href="https://numpy.org/doc/stable" target="_blank">ドキュメント</a> を確認することを忘れないでください。
  casestudies:
    title: ケーススタディ
    features:
      - 
        title: 世界初のブラックホール画像
        text: NumPyはどのように、SciPyやMatplotlibなどのNumPyに依存するライブラリとともに、イベントホライズンテレスコープによる世界初のブラックホール画像の作成を可能にしたのでしょうか。
        img: /images/content_images/case_studies/blackhole.png
        alttext: 世界初のブラックホール画像。黒い背景にオレンジ色の円で描かれています。
        url: /ja/case-studies/blackhole-image
      - 
        title: 重力波の検知
        text: 1916年、アルバート・アインシュタインは重力波を予言しました。100年後、LIGOの研究者たちはNumPyを使ってその存在を確認しました。
        img: /images/content_images/case_studies/gravitional.png
        alttext: 2つのオーブがお互いに周回し、周りの重力を変位させています。
        url: /ja/case-studies/gw-discov
      - 
        title: スポーツ分析
        text: クリケット分析は、統計的モデリングと予測分析によって選手やチームのパフォーマンスを向上させることで、クリケットの試合を変えようとしています。多くの分析が、NumPyにより可能になりました。
        img: /images/content_images/case_studies/sports.jpg
        alttext: 緑のフィールド上にあるクリケットボール。
        url: /ja/case-studies/cricket-analytics
      - 
        title: 深層学習による姿勢推定
        text: DeepLabCutはNumPyを利用し、動物の種類や時間スケールによらない運動制御の理解へ向け、動物の行動観察を含む科学技術研究を加速させています。
        img: /images/content_images/case_studies/deeplabcut.png
        alttext: チータの姿勢推定
        url: /ja/case-studies/deeplabcut-dnn
  tabs:
    title: NumPyのエコシステム
  section5: false
  navbar:
    - 
      title: インストール
      url: /install
    - 
      title: ドキュメント
      url: https://numpy.org/doc/stable
    - 
      title: 学習方法
      url: /learn
    - 
      title: コミュニティ
      url: /community
    - 
      title: 私たちについて
      url: /about
    - 
      title: ニュース
      url: /news
    - 
      title: 貢献
      url: /contribute
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - 
        link: https://github.com/numpy/numpy
        icon: github
      - 
        link: https://www.youtube.com/channel/UCguIL9NZ7ybWK5WQ53qbHng
        icon: youtube
      - 
        link: https://twitter.com/numpy_team
        icon: twitter
    quicklinks:
      column1:
        title: ""
        links:
          - 
            text: インストール
            link: /install
          - 
            text: ドキュメント
            link: https://numpy.org/doc/stable
          - 
            text: 学習方法
            link: /learn
          - 
            text: NumPy を引用する
            link: /citing-numpy
          - 
            text: ロードマップ
            link: https://numpy.org/neps/roadmap.html
      column2:
        links:
          - 
            text: 私達について
            link: /about
          - 
            text: コミュニティ
            link: /community
          - 
            text: ユーザ調査
            link: /user-surveys
          - 
            text: 貢献
            link: /contribute
          - 
            text: 行動規範
            link: /code-of-conduct
      column3:
        links:
          - 
            text: サポートを得る方法
            link: /gethelp
          - 
            text: 利用規約
            link: /terms
          - 
            text: プライバシーポリシー
            link: /privacy
          - 
            text: プレス用資料
            link: /press-kit
